name: React App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.4.0
    
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
    
    - name: Run tests
      run: pnpm test -- --passWithNoTests
    
    - name: Build
      run: pnpm build
